# coding: utf-8

"""
    OpenAPI Petstore

    This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from petstore_api.model_utils import (  # noqa: F401
    AnyTypeSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    FloatSchema,
    IntOrFloatSchema,
    DateSchema,
    DateTimeSchema,
    BoolSchema,
    FileSchema,
    NoneSchema,
    class_property,
    cached_property,
    isoparse,
    none_type,
    _get_discriminated_class_helper,
)



class Name(DictSchema):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Model for testing model name same as property name

    Attributes:
    name (int,): 
    snake_case (int,): 
    property (str,): 
    123Number (int,): 
    _additional_properties (Schema): the definition used for additional properties
        that are not defined in _properties
    """
    _required_property_names = {
        'name',
    }
    name = IntSchema
    snake_case = IntSchema
    _property = StrSchema
    locals()['property'] = _property
    del locals()['_property']
    _123_number = IntSchema
    locals()['123Number'] = _123_number
    del locals()['_123_number']

